---
name: Build Validation

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - "feature/**"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Filter changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            main:
              - 'infra/**'
            main_json:
              - 'infra/arm_output/main.json'

      - name: "Stale ARM Template"
        if: ${{ steps.filter.outputs.main == 'true' &&
          steps.filter.outputs.main_json == 'false' }}
        run: echo "::error::Stale ARM Template, please regenerate." && exit 1

      # MegaLinter
      - name: Lint code base
        id: megalinter
        uses: oxsecurity/megalinter@bacb5f8674e3730b904ca4d20c8bd477bc51b1a7 # v7.13.0
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
