---
name: Deploy OMOP OHDSI on Azure in Demo Environment
# This workflow is the integration build run for pushes to the main branch
# It also runs on a schedule, serving as the nightly build

on:  # yamllint disable-line rule:truthy
  schedule:
    # 2am each night https://crontab.guru/#0_1_*_*_*
    - cron: "0 2 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# This will prevent multiple runs of this entire workflow.
# We should NOT cancel in progress runs as that can destabilize the environment.
concurrency: "${{ github.workflow }}-${{ github.ref }}"

###############
# Set the Job #
###############
jobs:
  run_terraform:
    # Name the Job
    name: Run Terraform Environment
    # Set the agent to run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: demo

    ##################
    # Load all steps #
    ##################
    steps:
      # Need to check if the agent pool is ready first.
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        if: github.event_name == 'push'
        with:
          azure-devops-project-url: ${{ secrets.ADO_PROJECT_URL }} # e.g. https://dev.azure.com/<my-org>/<my-project>
          azure-pipeline-name: ${{ secrets.ENVIRONMENT_PIPELINE_NAME }}
          azure-devops-token: '${{ secrets.ADO_PAT }}'
